In [21]:
import pandas as pd
import numpy as np

In [22]:
df = pd.read_csv('dataset.CSV')
df.head()

                 time  temperature  humidity  pressure    lux
0   2022/3/12 22:32:2         24.2      32.7  98490.45  10.00
1   2022/3/12 22:32:6         24.0      33.9  98486.98  12.08
2  2022/3/12 22:32:11         24.1      33.9  98488.27  22.92
3  2022/3/12 22:32:16         24.1      33.8  98489.58  22.92
4  2022/3/12 22:32:21         24.1      35.0  98489.49  22.92

In [23]:
# Make a copy to avoid issues
df['time'] = pd.to_datetime(df['time'], errors='coerce')

# Extract datetime features
df['month'] = df['time'].dt.month
df['day'] = df['time'].dt.day
df['hour'] = df['time'].dt.hour
df['minute'] = df['time'].dt.minute
df['second'] = df['time'].dt.second
df['day_of_week'] = df['time'].dt.dayofweek  # Monday=0, Sunday=6

# Drop year to avoid overfitting
df['time_no_year'] = df['time'].dt.strftime("%m-%d %H:%M:%S")

df = df.drop(columns=['time'])  # optional if you want only processed features

df.head()

,temperature,humidity,pressure,lux,month,day,hour,minute,second,day_of_week,time_no_year
0,24.2,32.7,98490.45,10.00,3,12,22,32,2,5,03-12 22:32:02
1,24.0,33.9,98486.98,12.08,3,12,22,32,6,5,03-12 22:32:06
2,24.1,33.9,98488.27,22.92,3,12,22,32,11,5,03-12 22:32:11
3,24.1,33.8,98489.58,22.92,3,12,22,32,16,5,03-12 22:32:16
4,24.1,35.0,98489.49,22.92,3,12,22,32,21,5,03-12 22:32:21

In [24]:
df.describe()

,temperature,humidity,pressure,lux,month,day,hour,minute,second,day_of_week
count,693220.000000,693220.000000,693220.000000,693220.000000,693220.000000,693220.000000,693220.000000,693220.000000,693220.000000,693220.000000
mean,22.202527,39.228161,98639.567843,28.361270,3.539898,16.477162,11.448539,29.494839,29.500235,2.981088
std,1.040201,4.068492,984.714168,55.275148,0.498406,7.907144,6.917133,17.317685,17.318269,1.999729
min,19.000000,29.300000,96352.680000,0.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,21.600000,36.300000,97974.167500,0.420000,3.000000,11.000000,5.000000,14.000000,14.000000,1.000000
50%,22.300000,38.400000,98779.700000,1.250000,4.000000,17.000000,11.000000,29.000000,29.000000,3.000000
75%,23.000000,41.500000,99477.712500,27.920000,4.000000,22.000000,17.000000,44.000000,44.000000,5.000000
max,30.000000,56.900000,100301.060000,632.080000,4.000000,31.000000,23.000000,59.000000,59.000000,6.000000

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 693220 entries, 0 to 693219
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   temperature   693220 non-null  float64
 1   humidity      693220 non-null  float64
 2   pressure      693220 non-null  float64
 3   lux           693220 non-null  float64
 4   month         693220 non-null  int32
 5   day           693220 non-null  int32
 6   hour          693220 non-null  int32
 7   minute        693220 non-null  int32
 8   second        693220 non-null  int32
 9   day_of_week   693220 non-null  int32
 10  time_no_year  693220 non-null  object
dtypes: float64(4), int32(6), object(1)
memory usage: 42.3+ MB

In [26]:
X = df.drop(columns=['temperature', 'pressure', 'lux', 'time_no_year'])
Y = df['temperature']

In [27]:
X.head()

   humidity  month  day  hour  minute  second  day_of_week
0      32.7      3   12    22      32       2            5
1      33.9      3   12    22      32       6            5
2      33.9      3   12    22      32      11            5
3      33.8      3   12    22      32      16            5
4      35.0      3   12    22      32      21            5

In [28]:
df.head()

,temperature,humidity,pressure,lux,month,day,hour,minute,second,day_of_week,time_no_year
0,24.2,32.7,98490.45,10.00,3,12,22,32,2,5,03-12 22:32:02
1,24.0,33.9,98486.98,12.08,3,12,22,32,6,5,03-12 22:32:06
2,24.1,33.9,98488.27,22.92,3,12,22,32,11,5,03-12 22:32:11
3,24.1,33.8,98489.58,22.92,3,12,22,32,16,5,03-12 22:32:16
4,24.1,35.0,98489.49,22.92,3,12,22,32,21,5,03-12 22:32:21

In [29]:
df = df.drop(columns=['pressure', 'lux', 'time_no_year'])
df.head()

   temperature  humidity  month  day  hour  minute  second  day_of_week
0         24.2      32.7      3   12    22      32       2            5
1         24.0      33.9      3   12    22      32       6            5
2         24.1      33.9      3   12    22      32      11            5
3         24.1      33.8      3   12    22      32      16            5
4         24.1      35.0      3   12    22      32      21            5

In [30]:

df["humidity"] = df["humidity"] + 4
old_min, old_max = df["temperature"].min(), df["temperature"].max()
new_min, new_max = 10, 50

df["temperature"] = (df["temperature"] - old_min) * (new_max - new_min) / (old_max - old_min) + new_min

In [31]:
df.describe()

,temperature,humidity,month,day,hour,minute,second,day_of_week
count,693220.000000,693220.000000,693220.000000,693220.000000,693220.000000,693220.000000,693220.000000,693220.000000
mean,21.645553,43.228161,3.539898,16.477162,11.448539,29.494839,29.500235,2.981088
std,3.782548,4.068492,0.498406,7.907144,6.917133,17.317685,17.318269,1.999729
min,10.000000,33.300000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,19.454545,40.300000,3.000000,11.000000,5.000000,14.000000,14.000000,1.000000
50%,22.000000,42.400000,4.000000,17.000000,11.000000,29.000000,29.000000,3.000000
75%,24.545455,45.500000,4.000000,22.000000,17.000000,44.000000,44.000000,5.000000
max,50.000000,60.900000,4.000000,31.000000,23.000000,59.000000,59.000000,6.000000

In [32]:
df["target_temp"] = df["temperature"].shift(-1)
df = df.dropna()

In [33]:
X = df.drop(columns=["target_temp"])
y = df["target_temp"]

In [34]:
from sklearn.model_selection import train_test_split
# from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error


# # Train-test split (time-aware, no shuffle!)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# # Train model
# model = RandomForestRegressor(n_estimators=200, random_state=42)
# model.fit(X_train, y_train)

In [35]:
# # Predict
# y_pred = model.predict(X_test)

# # Evaluate
# mae = mean_absolute_error(y_test, y_pred)
# rmse = np.sqrt(mean_squared_error(y_test, y_pred))

# print("MAE:", mae)
# print("RMSE:", rmse)

# # Example: predict for the last row in test
# sample = X_test.iloc[-1]
# pred_temp = model.predict([sample])[0]

# print("Input:", sample.to_dict())
# print("Predicted Next Temperature:", pred_temp)

In [36]:
# from sklearn.linear_model import LinearRegression

# model = LinearRegression()
# model.fit(X_train, y_train)


# sample = X_test.iloc[-1]
# print(sample)
# model.predict([sample])[0]

In [37]:
# model.predict([[45, 99.9, 6, 3, 15, 56, 20, 0]])

In [38]:
# # Predict
# y_pred = model.predict(X_test)

# # Evaluate
# mae = mean_absolute_error(y_test, y_pred)
# rmse = np.sqrt(mean_squared_error(y_test, y_pred))

# print("MAE:", mae)
# print("RMSE:", rmse)

In [39]:
# from sklearn.metrics import r2_score

# r2 = r2_score(y_test, y_pred)
# print("R² Score:", r2*100)

In [40]:
from xgboost import XGBRegressor
model = XGBRegressor(n_estimators=200, max_depth=8, learning_rate=0.1)
model.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=True, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [41]:
# Predict
y_pred = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

print("MAE:", mae)
print("RMSE:", rmse)

MAE: 0.22443440305653287
RMSE: 0.2785178932176662

In [43]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print("R² Score:", r2*100)

R² Score: 97.83331164525617

In [ ]:
# from sklearn.linear_model import Lasso
# model = Lasso()
# model.fit(X_train, y_train)

In [ ]:
# # Predict
# y_pred = model.predict(X_test)

# # Evaluate
# mae = mean_absolute_error(y_test, y_pred)
# rmse = np.sqrt(mean_squared_error(y_test, y_pred))

# print("MAE:", mae)
# print("RMSE:", rmse)

In [ ]:
# model.predict([[20, 99.9, 6, 3, 15, 56, 20, 0]])

In [ ]:
import pickle

# Save the trained model
with open("temperature_predictor.pkl", "wb") as f:
    pickle.dump(model, f)

print("✅ Model saved as temperature_predictor.pkl")

✅ Model saved as temperature_predictor.pkl

In [ ]:
with open("temperature_predictor.pkl", "rb") as f:
    loaded_model = pickle.load(f)

# Test prediction with loaded model
sample = X_test.iloc[-1]
pred_temp = loaded_model.predict([sample])[0]

print("Predicted Next Temperature (from loaded model):", pred_temp)

Predicted Next Temperature (from loaded model): 25.636790236514397

c:\Users\Malay\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
loaded_model.predict([[30, 99.9, 6, 3, 15, 56, 20, 0]])

c:\Users\Malay\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([30.01858576])